# Generated by Django 3.1.7 on 2021-03-09 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0002_letter_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='message',
            field=models.TextField(max_length=3000, verbose_name='письмо'),
        ),
    ]
