# Generated by Django 3.1.7 on 2021-03-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210310_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current',
            field=models.IntegerField(default=0, verbose_name='current_letter_id'),
        ),
    ]
