# Generated by Django 3.1.7 on 2021-03-11 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_current'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='saves',
            new_name='bookmarks',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='current',
            new_name='current_letter',
        ),
    ]
