# Generated by Django 3.1.7 on 2021-03-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210311_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_write',
            field=models.BooleanField(default=True, verbose_name='может отправить'),
        ),
        migrations.AlterField(
            model_name='user',
            name='current_letter',
            field=models.IntegerField(default=0, verbose_name='активное письмо'),
        ),
    ]
